HW1 - Python Refresher <br>

This exercise will help you practice numpy and pandas, which are important day to day tools for data scientists/analysts. <br>
<b> You are required to do this exercise alone!<b> <br>

In [1]:
import numpy as np
import pandas as pd
np.random.seed(100)

# Numpy

In this section, you are required to solve the following questions using numpy methods.<br>
When asked to create an array, do not hard code it. For example: create an array from 1 to 5 => np.array([1,2,3,4,5]
) is not an acceptable solution.<br>
<b>Please note: The following questions are solvable without numpy methods, but if you choose to do so, points will be reduced<b>

create an array that contains all the even numbers from 0 to 20 (including)

In [2]:
array=np.arange(0,21,2)
print("Array of all the even integers from 0 to 20")
print(array) 

Array of all the even integers from 0 to 20
[ 0  2  4  6  8 10 12 14 16 18 20]


create a 4*3 matrix that contains only the value 4.3

In [3]:
np.full((4, 3), 4.3)

array([[4.3, 4.3, 4.3],
       [4.3, 4.3, 4.3],
       [4.3, 4.3, 4.3],
       [4.3, 4.3, 4.3]])

create an array of length 10, which contains evenly spaced numbers between 3 and 7 (including)<br>
For example: [0, 0.25, 0.5, .0.75, 1.0], is a 5 element array that the distance between every 2 adjacent numbers is 0.25.


In [4]:
np.linspace(3,7,10)

array([3.        , 3.44444444, 3.88888889, 4.33333333, 4.77777778,
       5.22222222, 5.66666667, 6.11111111, 6.55555556, 7.        ])

create a 5x5 array, in which the elements are drawn from a normal distribution (mean=0 and standard deviation=1)

In [5]:
np.random.standard_normal(size=(5, 5))

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079],
       [ 0.51421884,  0.22117967, -1.07004333, -0.18949583,  0.25500144],
       [-0.45802699,  0.43516349, -0.58359505,  0.81684707,  0.67272081],
       [-0.10441114, -0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574,  0.18451869]])

create an identity  5*5 matrix

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

return elements of the array, that are located at even indexes <br>
array = [0,1,2,3,4,5,6,7,8,9]

In [7]:
arr = np.arange(10)
arr[0::2]

array([0, 2, 4, 6, 8])

concatenate the following arrays - row wise

In [8]:
a = np.zeros([4, 4])
b = np.ones([4, 4])
np.concatenate((a, b), axis=0)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

concatenate the following arrays - column wise

In [9]:
a = np.zeros([4, 4])
b = np.ones([4, 4])
np.concatenate((a, b), axis=1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

Find the index of the 5th repetition of the number 1 in the array<br>
For example: [1,1,1,2,2,1,1] -> should return 6

In [10]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
np.where(x == 1)[0][4]

8

compute the euclidean distance between arrays a and b

In [11]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
dist = np.linalg.norm(a - b)
print(dist)

6.708203932499369


Drop all nan values from the array

In [12]:
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])
arr = arr[~np.isnan(arr)]
arr

array([1., 2., 3., 5., 6., 7.])

return the maximum value for each row in the given array.

In [13]:
a = np.random.randint(1,10, [5,3])
maxInRows = np.amax(a, axis=1)
print('Max value of every Row: ', maxInRows)

Max value of every Row:  [6 9 6 7 8]


return the maximum value for each column in the given array (same array as in the previous question).

In [14]:
maxIncol = np.amax(a, axis=0)
print('Max value of every col: ', maxIncol)

Max value of every col:  [8 9 5]


Return the most frequent number in the numpy array<br>
For example: [1,2,3,3,3,4,5] -> should return 3

In [15]:
arr = np.random.randint(1,10, [1,1000])
values = np.unique(arr)
print("Most frequent value in the array:", values[0])

Most frequent value in the array: 1


Get the positions(indexes) of the top 5 maximum elements in the given array <br>
For example: [8,1,9,3,4,7,5] -> should return [0,2,4,5,6]

In [16]:
a = np.random.uniform(1,50, 20)
top_5 = np.argpartition(-a,5)
np.sort(top_5[:5])

array([ 2,  4,  5,  6, 13], dtype=int64)

Get the values of the top 5 maximum elements in the given array (same array as in the previous question)<br>
For example: [8,1,9,3,4,7,5] -> should return [8,9,4,7,5]

In [17]:
top_5 = a[np.argpartition(-a,5)]
top_5[:5]

array([49.35438869, 48.96251517, 47.48561434, 38.37693608, 36.5578287 ])

replace all missing values in the array with the value 4

In [18]:
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])
arr[np.isnan(arr)] = 4
arr

array([1., 2., 3., 4., 5., 6., 7., 4.])

# Pandas

In this part, you will analyze a given data set using Pandas.
Use the techniques seen in class and explore the web for more required methods.
The data set contains nan values. It is up to you to find a solution to handle this.

read the Salaries csv into a dataframe

In [19]:
df = pd.read_csv('Salaries.csv')

C:\Users\chris\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (12) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


how many entries are there in the data set

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148650 entries, 0 to 148649
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148650 non-null  int64  
 1   EmployeeName      148650 non-null  object 
 2   JobTitle          148650 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148650 non-null  float64
 8   TotalPayBenefits  148650 non-null  float64
 9   Year              148650 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148650 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(7), int64(2), object(4)
memory usage: 14.7+ MB


print the dataframes' first 15 lines 

In [21]:
df.head(15)

Id        EmployeeName                                          JobTitle  \
0    1      NATHANIEL FORD    GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1    2        GARY JIMENEZ                   CAPTAIN III (POLICE DEPARTMENT)   
2    3      ALBERT PARDINI                   CAPTAIN III (POLICE DEPARTMENT)   
3    4   CHRISTOPHER CHONG              WIRE ROPE CABLE MAINTENANCE MECHANIC   
4    5     PATRICK GARDNER      DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
5    6      DAVID SULLIVAN                         ASSISTANT DEPUTY CHIEF II   
6    7           ALSON LEE                BATTALION CHIEF, (FIRE DEPARTMENT)   
7    8       DAVID KUSHNER                    DEPUTY DIRECTOR OF INVESTMENTS   
8    9      MICHAEL MORRIS                BATTALION CHIEF, (FIRE DEPARTMENT)   
9   10  JOANNE HAYES-WHITE            CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)   
10  11       ARTHUR KENNEY  ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)   
11  12    PATRICIA JACKSON                   CAPTAIN III (POLICE DEPARTMENT)   
12  13   EDWARD HARRINGTON                       EXECUTIVE CONTRACT EMPLOYEE   
13  14         JOHN MARTIN                                 DEPARTMENT HEAD V   
14  15      DAVID FRANKLIN                BATTALION CHIEF, (FIRE DEPARTMENT)   

      BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0   167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1   155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2   212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3    77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4   134401.60      9737.00  182234.59       NaN  326373.19         326373.19   
5   118602.00      8601.00  189082.74       NaN  316285.74         316285.74   
6    92492.01     89062.90  134426.14       NaN  315981.05         315981.05   
7   256576.96         0.00   51322.50       NaN  307899.46         307899.46   
8   176932.64     86362.68   40132.23       NaN  303427.55         303427.55   
9   285262.00         0.00   17115.73       NaN  302377.73         302377.73   
10  194999.39     71344.88   33149.90       NaN  299494.17         299494.17   
11   99722.00     87082.62  110804.30       NaN  297608.92         297608.92   
12  294580.02         0.00       0.00       NaN  294580.02         294580.02   
13  271329.03         0.00   21342.59       NaN  292671.62         292671.62   
14  174872.64     74050.30   37424.11       NaN  286347.05         286347.05   

    Year  Notes         Agency Status  
0   2011    NaN  San Francisco    NaN  
1   2011    NaN  San Francisco    NaN  
2   2011    NaN  San Francisco    NaN  
3   2011    NaN  San Francisco    NaN  
4   2011    NaN  San Francisco    NaN  
5   2011    NaN  San Francisco    NaN  
6   2011    NaN  San Francisco    NaN  
7   2011    NaN  San Francisco    NaN  
8   2011    NaN  San Francisco    NaN  
9   2011    NaN  San Francisco    NaN  
10  2011    NaN  San Francisco    NaN  
11  2011    NaN  San Francisco    NaN  
12  2011    NaN  San Francisco    NaN  
13  2011    NaN  San Francisco    NaN  
14  2011    NaN  San Francisco    NaN

print the dataframes' last 20 lines

In [22]:
df.tail(20)

Id            EmployeeName                      JobTitle  BasePay  \
148630  148631            Randy J Keys                     Carpenter      0.0   
148631  148632         Andre M Johnson   Communications Dispatcher 1      0.0   
148632  148633  Sharon D Owens-Webster    Protective Services Worker      0.0   
148633  148634        Edward Ferdinand               General Laborer      0.0   
148634  148635          David M Turner           Transit Car Cleaner      0.0   
148635  148636     James S Kibblewhite               General Laborer      0.0   
148636  148637           Andrew J Enzi           Arborist Technician      0.0   
148637  148638        Kadeshra D Green        Transit Fare Inspector      0.0   
148638  148639    Lennard B Hutchinson                   Electrician      0.0   
148639  148640       Richard A Talbert                     Custodian      0.0   
148640  148641      Charlene D Mccully       Parking Control Officer      0.0   
148641  148642   Raphael Marquis Goins                  Museum Guard      0.0   
148642  148643       Dominic C Marquez                   Sign Worker      0.0   
148643  148644              Kim Brewer       Parking Control Officer      0.0   
148644  148645            Randy D Winn  Stationary Eng, Sewage Plant      0.0   
148645  148646        Carolyn A Wilson     Human Services Technician      0.0   
148646  148648          Joann Anderson   Communications Dispatcher 2      0.0   
148647  148649             Leon Walker                     Custodian      0.0   
148648  148650           Roy I Tillery                     Custodian      0.0   
148649  148654               Joe Lopez    Counselor, Log Cabin Ranch      0.0   

        OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
148630          0.0      0.00       0.0      0.00              0.00  2014   
148631          0.0      0.00       0.0      0.00              0.00  2014   
148632          0.0      0.00       0.0      0.00              0.00  2014   
148633          0.0      0.00       0.0      0.00              0.00  2014   
148634          0.0      0.00       0.0      0.00              0.00  2014   
148635          0.0      0.00       0.0      0.00              0.00  2014   
148636          0.0      0.00       0.0      0.00              0.00  2014   
148637          0.0      0.00       0.0      0.00              0.00  2014   
148638          0.0      0.00       0.0      0.00              0.00  2014   
148639          0.0      0.00       0.0      0.00              0.00  2014   
148640          0.0      0.00       0.0      0.00              0.00  2014   
148641          0.0      0.00       0.0      0.00              0.00  2014   
148642          0.0      0.00       0.0      0.00              0.00  2014   
148643          0.0      0.00       0.0      0.00              0.00  2014   
148644          0.0      0.00       0.0      0.00              0.00  2014   
148645          0.0      0.00       0.0      0.00              0.00  2014   
148646          0.0      0.00       0.0      0.00              0.00  2014   
148647          0.0      0.00       0.0      0.00              0.00  2014   
148648          0.0      0.00       0.0      0.00              0.00  2014   
148649          0.0   -618.13       0.0   -618.13           -618.13  2014   

        Notes         Agency Status  
148630    NaN  San Francisco     PT  
148631    NaN  San Francisco     PT  
148632    NaN  San Francisco     PT  
148633    NaN  San Francisco     PT  
148634    NaN  San Francisco     PT  
148635    NaN  San Francisco     PT  
148636    NaN  San Francisco     PT  
148637    NaN  San Francisco     PT  
148638    NaN  San Francisco     PT  
148639    NaN  San Francisco     PT  
148640    NaN  San Francisco     PT  
148641    NaN  San Francisco     PT  
148642    NaN  San Francisco     PT  
148643    NaN  San Francisco     PT  
148644    NaN  San Francisco     PT  
148645    NaN  San Francisco     PT  
148646    NaN  San Francisco     PT  
148647  

print the column names

In [23]:
print(df.columns) 

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='object')


what is the average BasePay

In [24]:
df["BasePay"].mean()

66325.44884050643

what is the highest amount of OvertimePay

In [25]:
df["OvertimePay"].max()

245131.88

extract the rows where EmployeeName == JOSEPH DRISCOLL (case insensitive)

In [26]:
df.loc[df["EmployeeName"].str.lower() ==  "JOSEPH DRISCOLL".lower(),:] 

Id     EmployeeName                   JobTitle    BasePay  \
24        25  JOSEPH DRISCOLL  CAPTAIN, FIRE SUPPRESSION  140546.86   
36198  36199  Joseph Driscoll  Captain, Fire Suppression  145658.98   

       OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
24        97868.77  31909.28       NaN  270324.91         270324.91  2011   
36198    114513.29  28743.36  42919.16  288915.63         331834.79  2012   

       Notes         Agency Status  
24       NaN  San Francisco    NaN  
36198    NaN  San Francisco    NaN

who is the highest paid person (including benefits) in 2013?

In [27]:
year_1 = df.loc[df["Year"] == 2013]
year_1.sort_values(by=['TotalPayBenefits'])
year_1.iloc[0]

Id                            72926
EmployeeName         Gregory P Suhr
JobTitle            Chief of Police
BasePay                      319275
OvertimePay                       0
OtherPay                    20007.1
Benefits                    86533.2
TotalPay                     339282
TotalPayBenefits             425815
Year                           2013
Notes                           NaN
Agency                San Francisco
Status                          NaN
Name: 72925, dtype: object

who is the lowest paid person (including benefits) in 2011?

In [28]:
year_1 = df.loc[df["Year"] == 2011]
year_1[year_1['TotalPayBenefits'] == year_1['TotalPayBenefits'].min()]

Id        EmployeeName                                    JobTitle  \
36156  36157      PAULETTE ADAMS  STATIONARY ENGINEER, WATER TREATMENT PLANT   
36157  36158       KAUKAB MOHSIN                            TRANSIT OPERATOR   
36158  36159  JOSEPHINE MCCREARY                                  MANAGER IV   

       BasePay  OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  \
36156      0.0          0.0       0.0       NaN       0.0               0.0   
36157      0.0          0.0       0.0       NaN       0.0               0.0   
36158      0.0          0.0       0.0       NaN       0.0               0.0   

       Year  Notes         Agency Status  
36156  2011    NaN  San Francisco    NaN  
36157  2011    NaN  San Francisco    NaN  
36158  2011    NaN  San Francisco    NaN

what is the mean BasePay per year (2011-2014)

In [29]:
df.groupby('Year').mean()['BasePay']

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

how many unique job titles are there?

In [30]:
print("There are,", df["JobTitle"].str.lower().nunique(), "unique job titles")

There are, 1636 unique job titles


what are the 5 most common jobs?

In [31]:
n = 5
df['JobTitle'].value_counts()[:n].index.tolist()

['Transit Operator',
 'Special Nurse',
 'Registered Nurse',
 'Public Svc Aide-Public Works',
 'Police Officer 3']

how many people have the word 'chief' in their job title?

In [32]:
df["JobTitle"].str.lower().str.contains("chief").sum()

627

what is the total sum of "OtherPay" in 2012

In [33]:
df["OtherPay"].loc[df["Year"] == 2012].sum()

134322286.19

how many people with Status == 'FT' are there?

In [34]:
df["Status"].str.count("FT").sum()

22334.0

how much did EmployeeName == "A Bernard Fatooh" (case insensitive) earn (including benefits) from 2011 to 2014 (including)

In [35]:
df.loc[df["EmployeeName"].str.lower() == "A Bernard Fatooh".lower(),:]["TotalPayBenefits"].sum()

73707.79

how many "account clerks" are there?

In [36]:
df["JobTitle"].str.lower().str.contains("account clerk").sum()

1089